<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<UseWindowsForms>true</UseWindowsForms>
		<ImplicitUsings>enable</ImplicitUsings>
		<NoWarn>IDE1006;SYSLIB1054;SYSLIB1045;CA2249;</NoWarn>
		<ApplicationIcon>1409863574410756177.ico</ApplicationIcon>
		<SatelliteResourceLanguages>en;zh-TW</SatelliteResourceLanguages>
		<PlatformTarget>x64</PlatformTarget>
	</PropertyGroup>

	<!--<ItemGroup>
		<Content Include="..\X264GUI\bin\Debug\bin\**\*.*">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
	</ItemGroup>-->

	<ItemGroup>
		<Content Include="..\bin\Debug\bin\ffmpeg\*.*">
			<Link>.\bin\ffmpeg\%(Filename)%(Extension)</Link>
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
			<Visible>false</Visible>
		</Content>
	</ItemGroup>
	<ItemGroup>
		<Content Include="..\bin\Debug\bin\eac3to\*.*">
			<Link>.\bin\eac3to\%(Filename)%(Extension)</Link>
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
			<Visible>false</Visible>
		</Content>
	</ItemGroup>
	<ItemGroup>
		<Content Include="..\bin\Debug\bin\x264\*.*">
			<Link>.\bin\x264\%(Filename)%(Extension)</Link>
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
			<Visible>false</Visible>
		</Content>
	</ItemGroup>
	<ItemGroup>
		<Content Include="..\bin\Debug\bin\HashMyFiles\*.*">
			<Link>.\bin\HashMyFiles\%(Filename)%(Extension)</Link>
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
			<Visible>false</Visible>
		</Content>
	</ItemGroup>
	<ItemGroup>
	  <Content Include="1409863574410756177.ico" />
	</ItemGroup>
	<ItemGroup>
	  <PackageReference Include="Dapper" Version="2.1.72" />
	  <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.7" />
	  <PackageReference Include="WindowsAPICodePack" Version="8.0.15.1" />
	</ItemGroup>
	<ItemGroup>
	  <None Update="runtime-desktop-8.0.26-windows-x64-installer.txt">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </None>
	</ItemGroup>

	<Target Name="Git" BeforeTargets="BeforeBuild">
		<Message Text="取得 GIT HEAD TAG..." Importance="High" />
		<Exec Command="git rev-parse --short HEAD" IgnoreExitCode="true" ConsoleToMSBuild="true">
			<Output TaskParameter="ConsoleOutput" PropertyName="_gitHash" />
		</Exec>

		<ItemGroup>
			<AssemblyAttribute Include="X264GUIv2.Version.HashAttribute">
				<_Parameter1>$(_gitHash)</_Parameter1>
			</AssemblyAttribute>
		</ItemGroup>
		
		<Message Text="取得 GIT HEAD 時間..." Importance="High" />
		<Exec Command="git log -1 --format=&quot;%25%25cd&quot; --date=format-local:%25%25Y%25%25m%25%25dT%25%25H%25%25M" IgnoreExitCode="true" ConsoleToMSBuild="true">
			<Output TaskParameter="ConsoleOutput" PropertyName="_gitTime" />
		</Exec>

		<ItemGroup>
			<AssemblyAttribute Include="X264GUIv2.Version.TimeAttribute">
				<_Parameter1>$(_gitTime)</_Parameter1>
			</AssemblyAttribute>
		</ItemGroup>
	</Target>
</Project>